version: "3.8"
services:
  backend:
    build: .
    environment:
      DATABASE_URL: postgres://aircnc_app:aircnc@db:5432/aircnc
      NODE_ENV: production
    depends_on:
      - "db"
    command: ["./wait-for", "postgres:5432"]
    networks:
      backend:
    ports:
      - "8080:8080"

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: aircnc_app
      POSTGRES_PASSWORD: aircnc
      POSTGRES_DB: aircnc
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      backend:

networks:
  backend:
  frontend:

volumes:
  postgres-db: